// Generate the base64 card-art data-URLs the OG/social image inlines
// (ADR-055 amendment — OG image now features Pokémon card hero art).
//
// WHY: app/opengraph-image.tsx renders via next/og (Satori) on the EDGE runtime,
// which has no `fs`/`sharp` and can't read public/ at request time. Satori's WebP
// support is also unreliable, and the hero art in public/hero/ is .webp. So we
// convert the chosen cards webp -> optimized JPEG once at build time (Satori
// renders JPEG reliably), base64-inline them into a committed generated module,
// and the edge renderer just imports string constants (deterministic, no runtime
// fetch of our own origin, never 500s).
//
// Regenerate after changing the card selection:
//   node --experimental-strip-types --no-warnings scripts/generate-og-card-art.ts

import sharp from "sharp";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");

// The fan, in render order (first = back/left, last = front/right). All exist in
// public/hero/. base1-4 Charizard is the anchor; the other two are modern chase
// cards. Change this list + rerun to recompose the share card.
const CARDS = ["base1-4", "swsh7-215", "swsh4-188"] as const;

// Display width in the 1200x630 card is ~260-300px; 380px source is a crisp ~1.3x
// for X's in-feed render. JPEG q82 keeps the inlined base64 lean (cards are
// rectangular scans — no alpha needed; borderRadius + shadow come from Satori).
const TARGET_WIDTH = 380;
const JPEG_QUALITY = 82;

async function main(): Promise<void> {
  const entries: { slug: string; dataUrl: string }[] = [];
  let totalKb = 0;
  for (const slug of CARDS) {
    const src = join(ROOT, "public/hero", `${slug}.webp`);
    const buf = readFileSync(src);
    const jpeg = await sharp(buf)
      .resize({ width: TARGET_WIDTH })
      .jpeg({ quality: JPEG_QUALITY, mozjpeg: true })
      .toBuffer();
    const b64 = jpeg.toString("base64");
    const kb = Math.round((b64.length / 1024) * 10) / 10;
    totalKb += kb;
    console.log(`  ${slug}: jpeg ${Math.round(jpeg.length / 1024)}KB -> base64 ${kb}KB`);
    entries.push({ slug, dataUrl: `data:image/jpeg;base64,${b64}` });
  }
  console.log(`  total base64: ${Math.round(totalKb)}KB (inlined into the edge OG module)`);

  const out =
    `// GENERATED by scripts/generate-og-card-art.ts — do not edit by hand.\n` +
    `// Base64 JPEG of the OG/social hero cards (webp -> jpeg via sharp; Satori's\n` +
    `// webp support is unreliable on the edge runtime, so we inline reliable jpeg\n` +
    `// data-URLs at build time — no fs/sharp/fetch at edge request time). Cards:\n` +
    `//   ${CARDS.join(", ")}\n` +
    `// Regenerate: node --experimental-strip-types --no-warnings scripts/generate-og-card-art.ts\n\n` +
    `export const OG_CARD_ART: ReadonlyArray<{ slug: string; dataUrl: string }> = [\n` +
    entries.map((e) => `  { slug: ${JSON.stringify(e.slug)}, dataUrl: ${JSON.stringify(e.dataUrl)} },`).join("\n") +
    `\n];\n`;

  const dest = join(ROOT, "app/og-card-art.generated.ts");
  writeFileSync(dest, out, "utf8");
  console.log(`  wrote ${dest}`);
}

main().catch((err) => {
  console.error("generate-og-card-art failed:", (err as Error).message);
  process.exit(1);
});
